name: stock_and_inventory_software
description: "App ya kuscan bidhaa na kusimamia stoo."
publish_to: 'none'
version: 1.1.72

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Core Packages
  supabase_flutter: ^2.10.3
  mobile_scanner: ^5.1.1
  in_app_update: ^4.2.2
  window_manager: ^0.5.1
  package_info_plus: ^9.0.0
  dio: ^5.9.0

  url_launcher: ^6.1.7
  image: ^4.2.0

  flutter_tesseract_ocr: ^0.4.0
  qr_flutter: ^4.0.0
  flutter_file_dialog: ^3.0.2
  flutter_pdfview: ^1.0.0
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.1+1
  path: ^1.9.1
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  crypto: ^3.0.6
  flutter_quill: ^11.4.1
  google_fonts: ^6.1.0
  screenshot: ^3.0.0
  syncfusion_flutter_xlsio: ^29.2.11
  multicast_dns: ^0.3.0
  video_player: ^2.8.2
  webview_windows: ^0.4.0
  file_saver: ^0.2.13
  shared_preferences: ^2.5.2
  file_picker: ^10.0.0
  image_picker: ^1.1.2
  csv: ^6.0.0
  fluttertoast: ^8.0.9
  permission_handler: ^12.0.1
  http: ^1.1.0
  excel: ^2.0.5
  dropdown_search: ^5.0.6
  intl_phone_number_input: ^0.7.5
  wifi_iot: ^0.3.19+2
  barcode_widget: ^2.0.4
  tray_manager: ^0.5.0
  speech_to_text: ^7.3.0
  youtube_player_flutter: ^9.1.1



  flutter_tts: ^3.5.0
  flutter_vlc_player: ^7.0.0


  platform_info: ^5.0.0

  network_info_plus: ^5.0.3

#  blue_thermal_printer: ^1.1.5





  pie_chart: ^5.4.0
  flutter_barcode_sdk: ^3.0.2
  flutter_cube: ^0.1.1
  flutter_dotenv: ^5.2.1
  encrypt: ^5.0.3
  timezone: ^0.10.0
  share_plus: ^11.0.0
  font_awesome_flutter: ^10.8.0
  mailer: ^6.4.1
  open_filex: ^4.7.0
  json_annotation: ^4.4.0
  webview_flutter: ^4.10.0
  android_alarm_manager_plus: ^4.0.7
  workmanager: ^0.9.0
  device_info_plus: ^11.5.0
  geolocator: ^14.0.2
  twilio_flutter: ^0.9.0
  screen_retriever: ^0.2.0
  cron: ^0.6.2
  flutter_background_service: ^5.1.0
  flutter_email_sender: ^7.0.0
  path_provider: ^2.0.10
  pdf: ^3.6.0
  printing: ^5.14.2
  connectivity_plus: ^6.1.3
  camera: ^0.10.5
  video_player_web: ^2.0.0
  flutter_inappwebview: ^6.0.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.5.0

dependency_overrides:
  http: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/backgroud.jpg
    - assets/OpenSans-Regular.ttf
    - assets/OpenSans-Bold.ttf
    - assets/logo.jpeg
    - assets/logo.png
    - assets/images/
    - assets/aggreement.png
    - assets/try.ico
    - assets/vlc/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
